### ISSUE TITLE
Cost-sensitive binary classification 

### ISSUE THREAD

**Issue by samKaranth** [david-cortes/costsensitive#8]
Can cost-sensitive classifier (say WeightedAllPairs) be used for binary classification problem. We noticed assertion error for all the methods except CostProportionateClassifier. Could you please explain why other methods are not suitable for binary classification.
And can you suggest which method would be appropriate for cost-sensitive binary classifier.

**Comment by david-cortes** [comment]
It doesn’t support those cases because then it simply reduces a single weighted binary classification problem, for which you do not need an additional library since these methods (other than CostProportionateClassifier) already assume that you have a weighted binary classifier. You can read the references for more details.
